import prisma from '#prisma';

const raceTypeAssignments = [
  { name: 'Aarakocra', race_types: ['BEASTFOLK'] },
  { name: 'Aasimar', race_types: ['CELESTIAL', 'HUMAN'] },
  { name: 'Air Genasi', race_types: ['ELEMENTAL', 'HUMAN'] },
  { name: 'Animagus Black Dog', race_types: ['BEAST', 'HUMAN'] },
  { name: 'Aqrabuamelu', race_types: ['BEASTFOLK'] },
  { name: 'Astral Elf', race_types: ['ELF', 'CELESTIAL'] },
  { name: 'Banshee', race_types: ['SPIRIT', 'UNDEAD'] },
  { name: 'Barbarian', race_types: ['HUMAN'] },
  { name: 'Bugbear', race_types: ['GOBLIN', 'BEASTFOLK'] },
  { name: 'Centaur', race_types: ['BEASTFOLK'] },
  { name: 'Ceremorphus', race_types: ['BEAST', 'DEMON'] },
  { name: 'Changeling', race_types: ['HUMAN', 'SPIRIT'] },
  { name: 'Chimera Ant', race_types: ['BEAST', 'BEASTFOLK'] },
  { name: 'Cleric', race_types: ['HUMAN'] },
  { name: 'Death Eater', race_types: ['HUMAN', 'DEMON'] },
  { name: 'Demihuman', race_types: ['BEASTFOLK', 'HUMAN'] },
  { name: 'Demon', race_types: ['DEMON'] },
  { name: 'Djinn', race_types: ['ELEMENTAL', 'SPIRIT'] },
  { name: 'Do S (monster Princess)', race_types: ['DEMON', 'HUMAN'] },
  { name: 'Dracula', race_types: ['UNDEAD', 'HUMAN'] },
  { name: 'Dragon', race_types: ['DRAGON'] },
  { name: 'Dragonnuet', race_types: ['DRAGON', 'BEASTFOLK'] },
  { name: 'Druid', race_types: ['HUMAN', 'PLANT'] },
  { name: 'Earth Genasi', race_types: ['ELEMENTAL', 'HUMAN'] },
  { name: 'Eladrin', race_types: ['ELF', 'SPIRIT'] },
  { name: 'Fairy', race_types: ['SPIRIT', 'BEASTFOLK'] },
  { name: 'Fire Genasi', race_types: ['ELEMENTAL', 'HUMAN'] },
  { name: 'Garkain', race_types: ['UNDEAD', 'BEAST'] },
  { name: 'Ghoul', race_types: ['UNDEAD'] },
  { name: 'Giff', race_types: ['BEASTFOLK'] },
  { name: 'Goblin', race_types: ['GOBLIN'] },
  { name: 'Golem', race_types: ['MACHINE', 'ELEMENTAL'] },
  { name: 'Goliath', race_types: ['GIANT', 'HUMAN'] },
  { name: 'Gorgon', race_types: ['BEAST', 'DEMON'] },
  { name: 'Hadozee', race_types: ['BEASTFOLK'] },
  { name: 'Harengon', race_types: ['BEASTFOLK'] },
  { name: 'Hobgoblin', race_types: ['GOBLIN'] },
  { name: 'Human', race_types: ['HUMAN'] },
  { name: 'Hydra', race_types: ['BEAST', 'DRAGON'] },
  { name: 'Kenku', race_types: ['BEASTFOLK'] },
  { name: 'Kobold', race_types: ['DRAGON', 'GOBLIN'] },
  { name: 'Leach', race_types: ['UNDEAD', 'BEAST'] },
  { name: 'Lizardfolk', race_types: ['BEASTFOLK'] },
  { name: 'Loxo', race_types: ['BEASTFOLK'] },
  { name: 'Mermaid', race_types: ['BEASTFOLK', 'SPIRIT'] },
  { name: 'Mind Flayer', race_types: ['DEMON', 'SPIRIT'] },
  { name: 'Minotaur', race_types: ['BEASTFOLK', 'GIANT'] },
  { name: 'Monk', race_types: ['HUMAN'] },
  { name: 'Mummy', race_types: ['UNDEAD'] },
  { name: 'Nadubi', race_types: ['DEMON', 'BEAST'] },
  { name: 'Orc', race_types: ['ORC'] },
  { name: 'Owlin', race_types: ['BEASTFOLK'] },
  { name: 'Paladin', race_types: ['HUMAN', 'CELESTIAL'] },
  { name: 'Phoenix', race_types: ['BEAST', 'ELEMENTAL', 'CELESTIAL'] },
  { name: 'Plasmoid', race_types: ['ELEMENTAL'] },
  { name: 'Quickstep', race_types: ['HUMAN'] },
  { name: 'Rakshasa', race_types: ['DEMON', 'BEASTFOLK'] },
  { name: 'Ranger', race_types: ['HUMAN'] },
  { name: 'Reaper', race_types: ['SPIRIT', 'UNDEAD'] },
  { name: 'Rogue', race_types: ['HUMAN'] },
  { name: 'Satyr', race_types: ['BEASTFOLK', 'SPIRIT'] },
  { name: 'Sea Elf', race_types: ['ELF'] },
  { name: 'Shadar Kai', race_types: ['ELF', 'UNDEAD'] },
  { name: 'Shadow Knight', race_types: ['UNDEAD', 'HUMAN'] },
  { name: 'Siren', race_types: ['BEASTFOLK', 'SPIRIT'] },
  { name: 'Sorcerer', race_types: ['HUMAN'] },
  { name: 'Spirit', race_types: ['SPIRIT'] },
  { name: 'The Disembodied', race_types: ['SPIRIT', 'UNDEAD'] },
  { name: 'The Great Old One', race_types: ['DEMON', 'SPIRIT'] },
  { name: 'Thri Kreen', race_types: ['BEASTFOLK'] },
  { name: 'Trickster (loki)', race_types: ['CELESTIAL', 'SPIRIT'] },
  { name: 'Undead', race_types: ['UNDEAD'] },
  { name: 'Unicorn', race_types: ['BEAST', 'CELESTIAL'] },
  { name: 'Valkyrie', race_types: ['CELESTIAL', 'SPIRIT'] },
  { name: 'Vampire', race_types: ['UNDEAD', 'HUMAN'] },
  { name: 'Warforged', race_types: ['MACHINE'] },
  { name: 'Warlock', race_types: ['HUMAN', 'DEMON'] },
  { name: 'Water Genasi', race_types: ['ELEMENTAL', 'HUMAN'] },
  { name: 'Wendigo', race_types: ['UNDEAD', 'BEAST'] },
  { name: 'Werewolf', race_types: ['HUMAN', 'BEAST'] },
  { name: 'Witch', race_types: ['HUMAN', 'SPIRIT'] },
  { name: 'Zombie', race_types: ['UNDEAD'] },
];

// use the raceTypeAssignments to update the race records in the database
// Fetch first
const races = await prisma.race.findMany();
// Create a map.
const raceIdByName = Object.fromEntries(races.map(({ id, name }) => [name, id]));
// each record with the corresponding race using createMany
const data = raceTypeAssignments.flatMap(({ name, race_types }) =>
  race_types.map((type) => ({
    race_id: raceIdByName[name],
    type,
  })),
);

await prisma.race_types.createMany({
  data,
  skipDuplicates: true,
});
